### PR TITLE
keep files when save instance

### PR DESCRIPTION
**Pull request by marcaoas**

### CODE REVIEW

**Comment by byencho** [comment]
Hey just curious : did you notice some kind of bug you're trying to fix? If so I can try to address it in the main library repo.

**Comment by marcaoas** [comment]
hey there! not sure yet, I just notice that it is losing the state when navigating between fragments. I am just trying to figure out why. The problem was happing when navigating at the 3th level of the same fragment class it wasn't restoring the state saved. Any ideas?

**Comment by byencho** [comment]
For what it's worth, I haven't noticed anything like this in my own testing but it could be you are doing something I wasn't expecting.

**Comment by marcaoas** [comment]
I see, It is probably related with the fact I am using [the mulstistack library](https://github.com/JetradarMobile/android-multibackstack) to manage the stack then.

**Comment by byencho** [comment]
Ah, yeah I can't vouch for interactions with 3rd party libraries; my assumptions are based on typical Activities and Fragments under standard conditions. I think in your case you can feel free to remove the line you did, though. It's just an optimization that isn't technically required. Given a problem like this I might consider making this optional somehow in a future release.

**Comment by marcaoas** [comment]
Yeah, thats what I thought. The only problem I see is that I have to clean it up the data saved by my own, but I can't see another solution to this. 
I will create an issue in the main repository so we can discuss further then.
Thank you for the help!

**Comment by marcaoas** [comment]
Ok. I finish my tests here and that works for me. I am opening the issue on the main repo and as soon as possible I will send an pull request with the implementation you just said.
Thank you very much @byencho

**Comment by byencho** [comment]
Sounds good, thanks!

**Pull request merged**
